server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webnote
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379



springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  level:
    root: info
    com.walle.webnoteadmin.mapper: trace

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
