server:
  port: 80


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webnote
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  level:
    root: info
    com.walle.webnoteadmin.mapper: trace
